spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: emailesercizidev@gmail.com
    password: _Nuovapass0
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
